const { SlashCommandBuilder } = require("discord.js");
const config = require("../config");
const { successEmbed, errorEmbed, mainEmbed } = require("../utils/embeds");
const {
  popStock,
  addStock,
  serviceExists,
  getStockCount,
} = require("../utils/stockManager");
const {
  checkCooldown,
  setCooldown,
  formatRemaining,
} = require("../utils/cooldownManager");
const { canGenerate, isOwner } = require("../utils/permissions");
const { logGeneration } = require("../utils/logger");
const { serviceAutocomplete } = require("../utils/autocomplete");

module.exports = {
  data: new SlashCommandBuilder()
    .setName("gen")
    .setDescription("Generate an account from a service")
    .addStringOption((opt) =>
      opt
        .setName("service")
        .setDescription("The service to generate from")
        .setRequired(true)
        .setAutocomplete(true)
    ),

  async autocomplete(interaction) {
    await serviceAutocomplete(interaction);
  },

  async execute(interaction, client) {
    const service = interaction.options.getString("service");

    // Service exists?
    if (!serviceExists(service)) {
      return interaction.reply({
        embeds: [
          errorEmbed("Not Found", `No service named **${service}** exists.`),
        ],
        ephemeral: true,
      });
    }

    // Permission check
    if (!canGenerate(interaction.member)) {
      return interaction.reply({
        embeds: [
          errorEmbed(
            "Access Denied",
            "You need the generator role to use this command."
          ),
        ],
        ephemeral: true,
      });
    }

    // Cooldown
    if (!isOwner(interaction.user.id)) {
      const { onCooldown, remainingMs } = checkCooldown(
        interaction.user.id,
        config.COOLDOWN_TIME
      );

      if (onCooldown) {
        return interaction.reply({
          embeds: [
            errorEmbed(
              "On Cooldown",
              `Please wait **${formatRemaining(
                remainingMs
              )}** before generating again.`
            ),
          ],
          ephemeral: true,
        });
      }
    }

    // Stock check
    if (getStockCount(service) <= 0) {
      return interaction.reply({
        embeds: [
          errorEmbed(
            "Out of Stock",
            `**${service}** currently has no stock available.`
          ),
        ],
        ephemeral: true,
      });
    }

    await interaction.deferReply({ ephemeral: false });

    // Remove account from stock
    const account = popStock(service);

    if (!account) {
      return interaction.editReply({
        embeds: [
          errorEmbed(
            "Out of Stock",
            `**${service}** currently has no stock available.`
          ),
        ],
      });
    }

    // DM user
    const dmEmbed = mainEmbed(
      "🎁 Your Generated Account",
      `Here is your **${service}** account:\n\n\`\`\`\n${account}\n\`\`\``
    )
      .addFields(
        {
          name: "📦 Service",
          value: service,
          inline: true,
        },
        {
          name: "⚠️ Important",
          value: "Do not share this account.",
          inline: true,
        }
      )
      .setTimestamp();

    try {
      await interaction.user.send({ embeds: [dmEmbed] });
    } catch {
      addStock(service, [account]);

      return interaction.editReply({
        embeds: [
          errorEmbed(
            "DMs Closed",
            "Enable your DMs and try again."
          ),
        ],
      });
    }

    // Cooldown
    if (!isOwner(interaction.user.id)) {
      setCooldown(interaction.user.id);
    }

    const stockRemaining = getStockCount(service);

    await logGeneration(client, {
      user: interaction.user,
      service,
      stockRemaining,
    });

    // Public message
    const publicEmbed = mainEmbed(
      "🎉 Item Generated",
      "📩 **Sent to your DMs — Check your inbox.**"
    )
      .addFields(
        {
          name: "📦 Service",
          value: `\`${service}\``,
          inline: true,
        },
        {
          name: "📂 Type",
          value: "Account",
          inline: true,
        },
        {
          name: "👤 Generated By",
          value: `${interaction.user}`,
          inline: true,
        },
        {
          name: "📉 Stock Remaining",
          value: `${stockRemaining}`,
          inline: true,
        },
        {
          name: "⭐ Vouch",
          value: "Please leave a vouch after using the account!",
          inline: false,
        }
      )
      .setTimestamp();

    return interaction.editReply({
      embeds: [publicEmbed],
    });
  },
};
